pipeline:
  test:
    image: java:8
    commands:
      - java -version
      - ./gradlew test

  build:
    image: docker:1.13.1
    commands:
      - docker ps
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  development:
    image: docker/compose:1.8.1
    commands:
      - echo "DB_HOST=$(/sbin/ip route | awk '/default/ { print $3 }')" > .env
      - echo "DB_PORT=3307" >> .env
      - echo "DB_ROOT_PASSWORD=onkibot" >> .env
      - echo "DB_NAME=onkibot" >> .env
      - echo "DB_USERNAME=onkibot" >> .env
      - echo "DB_PASSWORD=onkibot" >> .env
      - docker-compose -f docker-compose.dev.yml build web
      - docker-compose -f docker-compose.dev.yml -p onkibot-backend-dev up -d web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      branch: development
      event: push

  production:
    image: docker/compose:1.8.1
    commands:
      - echo "DB_HOST=$(/sbin/ip route | awk '/default/ { print $3 }')" > .env
      - echo "DB_PORT=3306" >> .env
      - echo "DB_ROOT_PASSWORD=onkibot" >> .env
      - echo "DB_NAME=onkibot" >> .env
      - echo "DB_USERNAME=onkibot" >> .env
      - echo "DB_PASSWORD=onkibot" >> .env
      - docker-compose -f docker-compose.prod.yml build web
      - docker-compose -f docker-compose.prod.yml -p onkibot-backend-prod up -d web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:   
      branch: master
      event: push
