pipeline:
  # restores the cache from a local volume
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount: [ /drone/.gradle, /drone/.m2 ]
    volumes: /tmp/cache:/cache

  build:
    image: docker:1.13.1
    commands:
      - docker ps
      - ./deploy.sh
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # rebuild the cache in case new dependencies were downloaded
  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount: [ /drone/.gradle, /drone/.m2 ]
    volumes: /tmp/cache:/cache
