version: '2'

services:
  web:
    image: onkibot-backend:master
    build: .
    command: ./gradlew bootRun
    ports:
      - '127.0.0.1:8080:8080'
    depends_on:
      - db
    environment:
      - DOCKER_HOST_IP=${DOCKER_HOST_IP}
      - DOCKER_HOST_DB_PORT=3306
  db:
    image: mysql
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: onkibot
      MYSQL_DATABASE: onkibot
      MYSQL_USER: onkibot
      MYSQL_PASSWORD: onkibot
volumes:
  db_data:


