version: '2'

services:
  web:
    build: .
    command: ./gradlew bootRun
    ports:
      - '127.0.0.1:8080:8080'
    depends_on:
      - db
  db:
    image: mysql
    ports:
      - '127.0.0.1:3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: onkibot
      MYSQL_DATABASE: onkibot
      MYSQL_USER: onkibot
      MYSQL_PASSWORD: onkibot
volumes:
  db_data:
