spring.devtools.livereload.enabled: false

spring:
    datasource:
        url: jdbc:mysql://${DOCKER_HOST}/onkibot
        username: onkibot
        password: onkibot
        platform: mysql
        driverClassName: com.mysql.jdbc.Driver
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect

---
spring:
    profiles: production

# TODO: add the credentials to your production redis
# preferably using environment variables

# spring.profiles.active: redis
#    redis:
#      password:
#      host:
#      port:
